[workspace]
resolver = "2"
members = ["wgpu-in-app", "app-surface", "cargo-so"]
default-members = ["wgpu-in-app"]

[workspace.dependencies]
bytemuck = { version = "1.9.1", features = ["derive"] }
cgmath = "0.18"
glam = "0.20.5"
log = "0.4"
noise = { version = "0.7", default-features = false }
pollster = "0.2"
rand = { version = "0.7.2" }
wgpu = "0.15"
# wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "6147c918" }
hal = { git = "https://github.com/gfx-rs/wgpu", package = "wgpu-hal", version = "0.15" }

# wgpu = { path = "../../forks/wgpu/wgpu" }
# hal = { package = "wgpu-hal", path = "../../forks/wgpu/wgpu-hal" }

async-executor = "1.0"
winit = "0.27.1"
raw-window-handle = "0.5"
env_logger = "0.9"

# macOS, iOS
libc = "*"
objc = "*"
core-graphics = "*"
objc-foundation = "*"
lazy_static = "1.4"

# android target
android_logger = "0.10.1"
jni = "0.19"
jni_fn = "0.1"
ndk-sys = "*"
ash = "0.37.2"

# wasm target
web-sys = "0.3.60"
wasm-bindgen = "0.2.83"
js-sys = "0.3.60"
wasm-bindgen-futures = "0.4.33"
wee_alloc = "0.4.5"
# parking_lot 0.12 switches from `winapi` to `windows`; permit either
parking_lot = ">=0.11,<0.13"
