[package]
name = "wgpu-on-app"
authors = ["jinleili"]
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
default = []
angle = ["wgpu/angle"]
vulkan-portability = ["wgpu/vulkan-portability"]

[dependencies]
app-surface = { path = "./app-surface" }
bytemuck = { version = "1.9.1", features = ["derive"] }
cgmath = "0.18"
glam = "0.20.5"
log = "0.4"
noise = { version = "0.7", default-features = false }
pollster = "0.2"
rand = { version = "0.7.2" }
# wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "90eb399d" }
wgpu = { git = "https://github.com/jinleili/wgpu", rev = "5ff54710" }
# wgpu = { path = "../../forks/wgpu/wgpu" }

[target.'cfg(any(not(target_os = "ios"), not(target_os = "android")))'.dependencies]
async-executor = "1.0"
winit = "0.27.1"

[target.'cfg(target_os = "ios")'.dependencies]
env_logger = "0.9"
libc = "*"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.10.1"
jni = "0.19"
jni_fn = "0.1"
