[package]
authors = ["jinlei li<jinlei.li.work@outlook.com>"]
edition = "2021"
name = "wgpu-on-app"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
default = []

[dependencies]
app-surface = {path = "./app-surface"}
bytemuck = {version = "1.4", features = ["derive"]}
cgmath = "0.18"
log = "0.4.14"
noise = {version = "0.7", default-features = false}
pollster = "0.2"
rand = {version = "0.7.2"}
wgpu = {git = "https://github.com/gfx-rs/wgpu", rev = "6b4f1b84"}
# wgpu = {path = "../../forks/wgpu/wgpu"}

[target.'cfg(any(not(target_os = "ios"), not(target_os = "android")))'.dependencies]
async-executor = "1.0"
winit = "*"

[target.'cfg(target_os = "ios")'.dependencies]
env_logger = "0.9"
libc = "*"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.10.1"
jni = "0.19"
jni_fn = "0.1"
