[package]
name = "wgpu-on-ios"
version = "0.0.0"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"
resolver = "2"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = {git = "https://github.com/gfx-rs/wgpu", features = ["trace"], rev="69e86453"}
nalgebra-glm = "*"
zerocopy = "0.5"
image =  { version = "0.23", default-features = false, features = ["png"] }
pollster = "0.2"
lazy_static = "*"
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
objc = "*"
core-graphics = "*"
objc-foundation = "*"

