[package]
name = "wgpu-on-ios"
version = "0.0.0"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"
resolver = "2"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = {git = "https://github.com/gfx-rs/wgpu", features = ["trace"], rev="180e3e35"}
pollster = "0.2"
lazy_static = "*"
png = "0.16"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }
bytemuck = { version = "1.4", features = ["derive"] }
cgmath = "0.18"
objc = "*"
core-graphics = "*"
objc-foundation = "*"

