[package]
name = "wgpu-on-ios"
version = "0.0.0"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = {git = "https://github.com/gfx-rs/wgpu", features = ["trace"], rev="a1251dc3"}
# wgpu = {git = "https://github.com/kvark/wgpu", rev="97cfdc363f0f84460e305e0e8c31d0ea956c207b"}

pollster = "0.2"
lazy_static = "*"
png = "0.16"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }
bytemuck = { version = "1.4", features = ["derive"] }
cgmath = "0.18"
objc = "*"
core-graphics = "*"
objc-foundation = "*"
