[package]
name = "wgpu-on-ios"
version = "0.0.0"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2021"
resolver = "2"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = {git = "https://github.com/gfx-rs/wgpu", version="0.12", rev="f8a63c40"}
pollster = "0.2"
lazy_static = "*"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }
bytemuck = { version = "1.4", features = ["derive"] }
cgmath = "0.18"
objc = "*"
core-graphics = "*"
objc-foundation = "*"
