[package]
name = "cargo-so"
authors = ["jinleili"]
description = "Helps cargo build Android .so lib files"
repository = "https://github.com/jinleili/wgpu-on-app"
readme = "./README.MD"
keywords = ["android", "so", "ndk", "jni"]
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.1.2"

[dependencies]
cargo-subcommand = "0.7.0"
dunce = "1.0.2"
ndk-build = "0.5.0"
