[package]
authors = ["Jinlei Li<jinlei.li.work@outlook.com>"]
description = "Helps cargo build Android .so lib files"
edition = "2021"
keywords = ["android", "so", "ndk", "jni"]
license = "MIT OR Apache-2.0"
name = "cargo-so"
readme = "./README.MD"
repository = "https://github.com/jinleili/wgpu_on_app"
version = "0.1.2"

[dependencies]
cargo-subcommand = "0.5.0"
dunce = "1.0.1"
ndk-build = "0.4.3"
