[package]
name = "app-surface"
authors = ["jinleili"]
edition = "2021"
version = "0.1.1"

[lib]
crate-type = ["rlib", "cdylib"]

[profile.release]
strip = "all"

[features]
default = []

[dependencies]
log = "0.4"
pollster = "0.2"
wgpu = "0.14"
# wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "c927e810" }
# wgpu = { git = "https://github.com/jinleili/wgpu", rev = "5ff54710" }
# wgpu = { path = "../../../forks/wgpu/wgpu" }

[target.'cfg(any(not(target_os = "ios"), not(target_os = "android")))'.dependencies]
async-executor = "1.4.1"
winit = "0.27.1"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "*"
objc = "0.2.7"
raw-window-handle = "0.5"

[target.'cfg(target_os = "ios")'.dependencies]
core-graphics = "*"
env_logger = "0.9"
lazy_static = "1.4"
libc = "*"
objc = "0.2.7"
objc-foundation = "*"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.10.1"
jni = "0.19"
# 星号表示不锁定特定版本，在项目构建及运行时始终保持使用最新版本
ndk-sys = "*"
raw-window-handle = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "=0.3.60", features = [
    "Document",
    "Window",
    "Location"
] }
wasm-bindgen = "0.2.83"
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wee_alloc = { version = "0.4.5", optional = true }
