[package]
authors = ["jinleili"]
edition = "2021"
name = "app-surface"
version = "0.1.0"

[lib]
crate-type = ["rlib"]

[profile.release]
# Rust 1.59+
strip = "all"

[features]
default = []

[dependencies]
log = "0.4"
pollster = "0.2"
wgpu = {git = "https://github.com/gfx-rs/wgpu", rev = "cb7ad30d"}
# wgpu = {git = "https://github.com/jinleili/wgpu", rev = "2010fbbe"}
# wgpu = {path = "../../../forks/wgpu/wgpu"}

[target.'cfg(any(not(target_os = "ios"), not(target_os = "android")))'.dependencies]
async-executor = "1.0"
winit = "0.26"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "*"
objc = "0.2.7"
raw-window-handle = "0.4"

[target.'cfg(target_os = "ios")'.dependencies]
core-graphics = "*"
env_logger = "0.9"
lazy_static = "1.4"
libc = "*"
objc = "0.2.7"
objc-foundation = "*"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.10.1"
jni = "0.19"
ndk-sys = "*"
raw-window-handle = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wasm-bindgen = "0.2.79"
web-sys = {version = "=0.3.56", optional = true}
wee_alloc = {version = "0.4.5", optional = true}
